def notifyObj
node(""){
   env.WORKSPACE=pwd()


   stage("Checkout"){
        dir("ossim-ci") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/ossim-ci.git"
        }
        dir("omar-opencv3_2") {
            git branch: "${OSSIM_GIT_BRANCH}", url: "https://github.com/ossimlabs/omar-opencv3_2.git"
        }
        notifyObj = load "${env.WORKSPACE}/ossim-ci/jenkins/pipeline/notify.groovy"
   }
   try{
      stage("Build"){
//         sh """
//             ${env.WORKSPACE}/omar-opencv3_2/scripts/build.sh
//         """
         sh """
             pushd ${env.WORKSPACE}/omar-opencv3_2
             mkdir -p build
             pushd build
             cmake ..
             make -j4
             popd
             popd
             """
      }
   }
   catch(e){
        echo e.toString()
        currentBuild.result = "FAILED"
        notifyObj?.notifyFailed()
    }

  stage("Clean Workspace"){
     step([$class: 'WsCleanup'])
  }
}